### ISSUE TITLE
displays negative distance

### ISSUE THREAD

**Issue by lenkawamoto** [samuelmr/pebble-getback#1]
At several miles away from the stored location, I'm seeing negative yards being displayed.

Just a cursory glance at your code shows that you're copying (from 'dist_tuple') an int32_t value (at least , that's the implication from the variable name) into the variable 'distance' which is declared as an int16_t.  Perhaps declaring this variable to be int32_t would solve the problem.  I would expect, however, to use uint32_t for 'distance' AND for 'dist_tuple'... but not being familiar with the Pebble API nor what libraries you're using, the latter may be out of your control.

**Comment by samuelmr** [comment]
Great catch, thanks!

I used to do the metric/imperial conversion on the JavaScript side, and `int16_t` was sufficient on C since the distance was always rounded.

I changed the type of distance to `int32_t` as you suggested and pushed a new version of Get Back to the Pebble app store. Are you able to install the new version (2.2) and verify that it now shows distances longer than 20.4 miles?

Thank you again for the report.

**Comment by samuelmr** [comment]
Great catch, thanks!

I used to do the metric/imperial conversion on the JavaScript side, and
int16_t was sufficient on C since the distance was always rounded.

I changed the type of distance to uint32_t as you suggested and pushed a
new version of Get Back to the Pebble app store. Are you able to install
the new version (2.2) and verify that it now shows distances longer than
20.4 miles?

Thank you again for the report.

    Samuel

**Comment by lenkawamoto** [comment]
Is there an easy way to check that I have the newest version?  I unloaded and reloaded the app but an not sure if it was updated or not.

**Comment by samuelmr** [comment]
I'm not aware of an easy way. Usually I just delete the watchapp, go to the appstore and add the app to make sure. See some discussion about the subject on the [Pebble forums](http://forums.getpebble.com/discussion/11050/watch-app-updates-and-pebble-store).

**Comment by lenkawamoto** [comment]
I was able to confirm that I no longer see negative yards displayed at distances greater than 20.4 miles.  Thanks for the fix!
